### ISSUE TITLE
422 from API if 'incident_snip' is not included in payload

### ISSUE THREAD

**Issue by jwmatthews** [konveyor-ecosystem/kai#87]
I noticed that if I don't include `"incident_snip": "",` in the json payload I get back a 422.

I don't believe we want to use or require 'incident_snip' from the API.  
My understanding is that this maps to codeSnip in an analysis data such as
https://github.com/konveyor-ecosystem/kai/blob/main/example/analysis/coolstore/output.yaml#L226-L232

So we are asking for the source code at time of analysis to be passed in from codeSnip = incident_snip.

For our case, we are passing in the full file contents as they exist on disk, the assumption is they equal incident_snip.  It's possible in future maybe these things are not identical, but for now I think it'd make most sense to remove incident_snip and not use it.

**Comment by JonahSussman** [comment]
We are currently using incident_snip to generate the embeddings (which I know we're not using right now). There are two solutions to explore.

_Quick and easy_: Rip out all the places where incident_snip is required, and replace it with a blank string if the user doesn't give us one. Luckily we never pass this to the prompt so it's all good. It's used in `fuzzy_get_similar_incident` for the embeddings, but again since we are ignoring them this shouldn't be an issue.

_More involved_: Change how the embeddings are handled, using the actual file contents as opposed to the snip. Then we can "truly" remove the 

Going to code up the quick and easy one, and file an issue for later
